Check for virtual environment existence

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -15,6 +15,11 @@ function main () {
     if [[ -n "${python_exec}" ]]; then
         echo "Using Python executable: ${python_exec}"
 
+        if [[ -d .env ]]; then
+            echo "ERROR: Virtual environment already exists: .env" >&2
+            return 2
+        fi
+
         if [[ -z "${venv_exec}" ]]; then
             pip install virtualenv
         fi
